# -*- coding: utf-8 -*-
"""reddit-scrape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1meR08JFWJDc4nst2uJ7T1LzTwk4t6zsv
"""

!pip install praw
import praw
import pandas as pd
import datetime as dt

reddit = praw.Reddit(client_id='J9fpBzqFYjxrhA', \
                     client_secret='am87EA-SZB0LSDvh5zq6t_ho6wo', \
                     user_agent='Moodimedia', \
                     username='MarioLovesBDSM', \
                     password='lasvegas')

help(reddit.subreddit('television').top(limit=500))

LIMIT = 1000


movies = reddit.subreddit('movies').hot(limit=LIMIT)
television = reddit.subreddit('television').hot(limit=LIMIT)
gaming = reddit.subreddit('gaming').hot(limit=LIMIT)
cars = reddit.subreddit('cars').hot(limit=LIMIT)
diy = reddit.subreddit('diy').hot(limit=LIMIT)
cars = reddit.subreddit('offmychest').hot(limit=LIMIT)
advice = reddit.subreddit('advice').hot(limit=LIMIT)
politics = reddit.subreddit('politics').hot(limit=LIMIT)
offmychest = reddit.subreddit('offmychest').hot(limit=LIMIT)
paranormal = reddit.subreddit('nosleep').hot(limit=LIMIT)
science = reddit.subreddit('science').hot(limit=LIMIT)
anime = reddit.subreddit('anime').hot(limit=LIMIT)
tech = reddit.subreddit('technology').hot(limit=LIMIT)
photography = reddit.subreddit('photography').hot(limit=LIMIT)
manga = reddit.subreddit('manga').hot(limit=LIMIT)
music = reddit.subreddit('music').hot(limit=LIMIT)
books = reddit.subreddit('books').hot(limit=LIMIT)
general = reddit.subreddit('all').hot(limit=LIMIT)

from google.colab import drive
drive.mount('/content/drive')

for submission in television.top(limit=10):
  print(f"{submission.title} : {submission.selftext}")

movies_dict = {"title": [], "body": []}
television_dict = {"title": [], "body": []}
gaming_dict = {"title": [], "body": []}
cars_dict = {"title": [], "body": []}
diy_dict = {"title": [], "body": []}
cars_dict = {"title": [], "body": []}
advice_dict = {"title": [], "body": []}
politics_dict = {"title": [], "body": []}
offmychest_dict = {"title": [], "body": []}
paranormal_dict = {"title": [], "body": []}
science_dict = {"title": [], "body": []}
anime_dict = {"title": [], "body": []}
tech_dict = {"title": [], "body": []}
photography_dict = {"title": [], "body": []}
manga_dict = {"title": [], "body": []}
music_dict = {"title": [], "body": []}
books_dict = {"title": [], "body": []}
general_dict ={"title": [], "body": []}



television_dict["title"][10]

for submission in movies:
  movies_dict["title"].append(submission.title)
  movies_dict["body"].append(submission.selftext)

for submission in television:
  television_dict["title"].append(submission.title)
  television_dict["body"].append(submission.selftext)

for submission in gaming:
  gaming_dict["title"].append(submission.title)
  gaming_dict["body"].append(submission.selftext)

for submission in cars:
  cars_dict["title"].append(submission.title)
  cars_dict["body"].append(submission.selftext)

for submission in diy:
  diy_dict["title"].append(submission.title)
  diy_dict["body"].append(submission.selftext)

for submission in advice:
  advice_dict["title"].append(submission.title)
  advice_dict["body"].append(submission.selftext)

for submission in politics:
  politics_dict["title"].append(submission.title)
  politics_dict["body"].append(submission.selftext)

for submission in offmychest:
  offmychest_dict["title"].append(submission.title)
  offmychest_dict["body"].append(submission.selftext)

for submission in paranormal:
  paranormal_dict["title"].append(submission.title)
  paranormal_dict["body"].append(submission.selftext)

for submission in science:
  science_dict["title"].append(submission.title)
  science_dict["body"].append(submission.selftext)

for submission in anime:
  anime_dict["title"].append(submission.title)
  anime_dict["body"].append(submission.selftext)

for submission in tech:
  tech_dict["title"].append(submission.title)
  tech_dict["body"].append(submission.selftext)

for submission in photography:
  photography_dict["title"].append(submission.title)
  photography_dict["body"].append(submission.selftext)

for submission in manga:
  manga_dict["title"].append(submission.title)
  manga_dict["body"].append(submission.selftext)

for submission in music:
  music_dict["title"].append(submission.title)
  music_dict["body"].append(submission.selftext)

for submission in books:
  books_dict["title"].append(submission.title)
  books_dict["body"].append(submission.selftext)

for submission in general:
  general_dict["title"].append(submission.title)
  general_dict["body"].append(submission.selftext)

for submission in science:
  print(submission)

for submission in television:
  print(type(submission))

television_label = []
gaming_label = []
cars_label= []
diy_label = []
advice_label = []
politics_label = []
offmychest_label = []
paranormal_label = []
science_label = []
anime_label = []
tech_label = []
photography_label = []
manga_label = []
music_label = []
books_label = []
general_label = []
for i in range(600):
  television_label.append('television')
  gaming_label.append('gaming')
  cars_label.append('cars')
  diy_label.append('diy')
  advice_label.append('advice')
  politics_label.append('politics')
  offmychest_label.append('offmychest')
  paranormal_label.append('paranormal')
  science_label.append('science')
  anime_label.append('anime')
  tech_label.append('tech')
  photography_label.append('photography')
  manga_label.append('manga')
  music_label.append('music')
  books_label.append('books')
  general_label.append('general')

len(television_label)

TITLES = []

TITLES.extend(television_dict["title"])
TITLES.extend(gaming_dict["title"])
TITLES.extend(cars_dict["title"])
TITLES.extend(diy_dict["title"])
TITLES.extend(advice_dict["title"])
TITLES.extend(politics_dict["title"])
TITLES.extend(offmychest_dict["title"])
TITLES.extend(paranormal_dict["title"])
TITLES.extend(science_dict["title"])
TITLES.extend(anime_dict["title"])
TITLES.extend(tech_dict["title"])
TITLES.extend(photography_dict["title"])
TITLES.extend(manga_dict["title"])
TITLES.extend(music_dict["title"])
TITLES.extend(books_dict["title"])
TITLES.extend(general_dict["title"])

len(TITLES)

len(anime_dict["title"])

television = reddit.subreddit('television').hot(limit=5000)

title = []

for tv in television:
  title.append(tv.title)

len(title)

print(len((television_dict["title"])))
print(len((gaming_dict["title"])))
print(len((cars_dict["title"])))
print(len((diy_dict["title"])))
print(len((advice_dict["title"])))
print(len((politics_dict["title"])))
print(len((offmychest_dict["title"])))
print(len((paranormal_dict["title"])))
print(len((science_dict["title"])))
print(len((anime_dict["title"])))
print(len((tech_dict["title"])))
print(len((photography_dict["title"])))
print(len((manga_dict["title"])))
print(len((music_dict["title"])))
print(len((books_dict["title"])))
print(len((general_dict["title"])))

LIMIT = 1000


television_top = reddit.subreddit('television').top(limit=LIMIT)
gaming_top = reddit.subreddit('gaming').top(limit=LIMIT)
cars_top = reddit.subreddit('cars').top(limit=LIMIT)
diy_top = reddit.subreddit('diy').top(limit=LIMIT)
cars_top = reddit.subreddit('offmychest').top(limit=LIMIT)
advice_top = reddit.subreddit('advice').top(limit=LIMIT)
politics_top = reddit.subreddit('politics').top(limit=LIMIT)
offmychest_top = reddit.subreddit('offmychest').top(limit=LIMIT)
paranormal_top = reddit.subreddit('nosleep').top(limit=LIMIT)
science_top = reddit.subreddit('science').top(limit=LIMIT)
anime_top = reddit.subreddit('anime').top(limit=LIMIT)
tech_top = reddit.subreddit('technology').top(limit=LIMIT)
photography_top = reddit.subreddit('photography').top(limit=LIMIT)
manga_top = reddit.subreddit('manga').top(limit=LIMIT)
music_top = reddit.subreddit('music').top(limit=LIMIT)
books_top = reddit.subreddit('books').top(limit=LIMIT)
general_top = reddit.subreddit('all').top(limit=LIMIT)

television_dict_top = {"title": [], "body": []}
gaming_dict_top = {"title": [], "body": []}
cars_dict_top = {"title": [], "body": []}
diy_dict_top = {"title": [], "body": []}
cars_dict_top = {"title": [], "body": []}
advice_dict_top = {"title": [], "body": []}
politics_dict_top = {"title": [], "body": []}
offmychest_dict_top = {"title": [], "body": []}
paranormal_dict_top = {"title": [], "body": []}
science_dict_top = {"title": [], "body": []}
anime_dict_top = {"title": [], "body": []}
tech_dict_top = {"title": [], "body": []}
photography_dict_top = {"title": [], "body": []}
manga_dict_top = {"title": [], "body": []}
music_dict_top = {"title": [], "body": []}
books_dict_top = {"title": [], "body": []}
general_dict_top ={"title": [], "body": []}

for submission in television_top:
  television_dict_top["title"].append(submission.title)
  television_dict_top["body"].append(submission.selftext)

for submission in gaming_top:
  gaming_dict_top["title"].append(submission.title)
  gaming_dict_top["body"].append(submission.selftext)

for submission in cars_top:
  cars_dict_top["title"].append(submission.title)
  cars_dict_top["body"].append(submission.selftext)

for submission in diy_top:
  diy_dict_top["title"].append(submission.title)
  diy_dict_top["body"].append(submission.selftext)

for submission in advice_top:
  advice_dict_top["title"].append(submission.title)
  advice_dict_top["body"].append(submission.selftext)

for submission in politics_top:
  politics_dict_top["title"].append(submission.title)
  politics_dict_top["body"].append(submission.selftext)

for submission in offmychest_top:
  offmychest_dict_top["title"].append(submission.title)
  offmychest_dict_top["body"].append(submission.selftext)

for submission in paranormal_top:
  paranormal_dict_top["title"].append(submission.title)
  paranormal_dict_top["body"].append(submission.selftext)

for submission in science_top:
  science_dict_top["title"].append(submission.title)
  science_dict_top["body"].append(submission.selftext)

for submission in anime_top:
  anime_dict_top["title"].append(submission.title)
  anime_dict_top["body"].append(submission.selftext)

for submission in tech_top:
  tech_dict_top["title"].append(submission.title)
  tech_dict_top["body"].append(submission.selftext)

for submission in photography_top:
  photography_dict_top["title"].append(submission.title)
  photography_dict_top["body"].append(submission.selftext)

for submission in manga_top:
  manga_dict_top["title"].append(submission.title)
  manga_dict_top["body"].append(submission.selftext)

for submission in music_top:
  music_dict_top["title"].append(submission.title)
  music_dict_top["body"].append(submission.selftext)

for submission in books_top:
  books_dict_top["title"].append(submission.title)
  books_dict_top["body"].append(submission.selftext)

for submission in general_top:
  general_dict_top["title"].append(submission.title)
  general_dict_top["body"].append(submission.selftext)





photography_top = reddit.subreddit('photography').top(limit=LIMIT)

THE_TITLES = []

print((len(television_dict["title"])))
print((len(gaming_dict["title"])))
print((len(cars_dict["title"])))
print((len(diy_dict["title"])))
print((len(advice_dict["title"])))
print((len(politics_dict["title"])))
print((len(offmychest_dict["title"])))
print((len(paranormal_dict["title"])))
print((len(science_dict["title"])))
print((len(anime_dict["title"])))
print((len(tech_dict["title"])))
print((len(photography_dict["title"])))
print((len(manga_dict["title"])))
print((len(music_dict["title"])))
print((len(books_dict["title"])))
print((len(general_dict["title"])))
THE_TITLES = []

print((len(television_dict_top["title"])))
print((len(gaming_dict_top["title"])))
print((len(cars_dict_top["title"])))
print((len(diy_dict_top["title"])))
print((len(advice_dict_top["title"])))
print((len(politics_dict_top["title"])))
print((len(offmychest_dict_top["title"])))
print((len(paranormal_dict_top["title"])))
print((len(science_dict_top["title"])))
print((len(anime_dict_top["title"])))
print((len(tech_dict_top["title"])))
print((len(photography_dict_top["title"])))
print((len(manga_dict_top["title"])))
print((len(music_dict_top["title"])))
print((len(books_dict_top["title"])))
print((len(general_dict_top["title"])))

LIMIT = 1000


television_new = reddit.subreddit('television').new(limit=LIMIT)
gaming_new = reddit.subreddit('gaming').new(limit=LIMIT)
cars_new = reddit.subreddit('cars').new(limit=LIMIT)
diy_new = reddit.subreddit('diy').new(limit=LIMIT)
cars_new = reddit.subreddit('offmychest').new(limit=LIMIT)
advice_new = reddit.subreddit('advice').new(limit=LIMIT)
politics_new = reddit.subreddit('politics').new(limit=LIMIT)
offmychest_new = reddit.subreddit('offmychest').new(limit=LIMIT)
paranormal_new = reddit.subreddit('nosleep').new(limit=LIMIT)
science_new = reddit.subreddit('science').new(limit=LIMIT)
anime_new = reddit.subreddit('anime').new(limit=LIMIT)
tech_new = reddit.subreddit('technology').new(limit=LIMIT)
photography_new = reddit.subreddit('photography').new(limit=LIMIT)
manga_new = reddit.subreddit('manga').new(limit=LIMIT)
music_new = reddit.subreddit('music').new(limit=LIMIT)
books_new = reddit.subreddit('books').new(limit=LIMIT)
general_new = reddit.subreddit('all').new(limit=LIMIT)

television_dict_new = {"title": [], "body": []}
gaming_dict_new = {"title": [], "body": []}
cars_dict_new = {"title": [], "body": []}
diy_dict_new = {"title": [], "body": []}
cars_dict_new = {"title": [], "body": []}
advice_dict_new = {"title": [], "body": []}
politics_dict_new = {"title": [], "body": []}
offmychest_dict_new = {"title": [], "body": []}
paranormal_dict_new = {"title": [], "body": []}
science_dict_new = {"title": [], "body": []}
anime_dict_new = {"title": [], "body": []}
tech_dict_new = {"title": [], "body": []}
photography_dict_new = {"title": [], "body": []}
manga_dict_new = {"title": [], "body": []}
music_dict_new = {"title": [], "body": []}
books_dict_new = {"title": [], "body": []}
general_dict_new ={"title": [], "body": []}

for submission in television_new:
  television_dict_new["title"].append(submission.title)
  television_dict_new["body"].append(submission.selftext)

for submission in gaming_new:
  gaming_dict_new["title"].append(submission.title)
  gaming_dict_new["body"].append(submission.selftext)

for submission in cars_new:
  cars_dict_new["title"].append(submission.title)
  cars_dict_new["body"].append(submission.selftext)

for submission in diy_new:
  diy_dict_new["title"].append(submission.title)
  diy_dict_new["body"].append(submission.selftext)

for submission in advice_new:
  advice_dict_new["title"].append(submission.title)
  advice_dict_new["body"].append(submission.selftext)

for submission in politics_new:
  politics_dict_new["title"].append(submission.title)
  politics_dict_new["body"].append(submission.selftext)

for submission in offmychest_new:
  offmychest_dict_new["title"].append(submission.title)
  offmychest_dict_new["body"].append(submission.selftext)

for submission in paranormal_new:
  paranormal_dict_new["title"].append(submission.title)
  paranormal_dict_new["body"].append(submission.selftext)

for submission in science_new:
  science_dict_new["title"].append(submission.title)
  science_dict_new["body"].append(submission.selftext)

for submission in anime_new:
  anime_dict_new["title"].append(submission.title)
  anime_dict_new["body"].append(submission.selftext)

for submission in tech_new:
  tech_dict_new["title"].append(submission.title)
  tech_dict_new["body"].append(submission.selftext)

for submission in photography_new:
  photography_dict_new["title"].append(submission.title)
  photography_dict_new["body"].append(submission.selftext)

for submission in manga_new:
  manga_dict_new["title"].append(submission.title)
  manga_dict_new["body"].append(submission.selftext)

for submission in music_new:
  music_dict_new["title"].append(submission.title)
  music_dict_new["body"].append(submission.selftext)

for submission in books_new:
  books_dict_new["title"].append(submission.title)
  books_dict_new["body"].append(submission.selftext)

for submission in general_new:
  general_dict_new["title"].append(submission.title)
  general_dict_new["body"].append(submission.selftext)

print((str(len(television_dict_new["title"]))) + " : " + str((len(television_dict_new["body"]))))
print((str(len(gaming_dict_new["title"])) + " : " + str((len(gaming_dict_new["body"])))))
print((str(len(cars_dict_new["title"])) + " : " + str((len(cars_dict_new["body"])))))
print((str(len(diy_dict_new["title"])) + " : " + str((len(diy_dict_new["body"])))))
print((str(len(advice_dict_new["title"])) + " : " + str((len(advice_dict_new["body"])))))
print((str(len(politics_dict_new["title"])) + " : " + str((len(politics_dict_new["body"])))))
print((str(len(offmychest_dict_new["title"])) + " : " + str((len(offmychest_dict_new["body"])))))
print((str(len(paranormal_dict_new["title"])) + " : " + str((len(paranormal_dict_new["body"])))))
print((str(len(science_dict_new["title"])) + " : " + (str(len(science_dict_new["body"])))))
print((str(len(anime_dict_new["title"]) )+ " : " + str((len(anime_dict_new["body"])))))
print((str(len(tech_dict_new["title"])) + " : " + str((len(tech_dict_new["body"])))))
print((str(len(photography_dict_new["title"])) + " : " + str((len(photography_dict_new["body"])))))
print((str(len(manga_dict_new["title"])) + " : " + str((len(manga_dict_new["body"])))))
print((str(len(music_dict_new["title"])) + " : " + str((len(music_dict_new["body"])))))
print((str(len(books_dict_new["title"])) + " : " + str((len(books_dict_new["body"])))))
print((str(len(general_dict_new["title"])) + " : " + str((len(general_dict_new["body"])))))

print((str(len(television_dict_top["title"]))) + " : " + str((len(television_dict_top["body"]))))
print((str(len(gaming_dict_top["title"])) + " : " + str((len(gaming_dict_top["body"])))))
print((str(len(cars_dict_top["title"])) + " : " + str((len(cars_dict_top["body"])))))
print((str(len(diy_dict_top["title"])) + " : " + str((len(diy_dict_top["body"])))))
print((str(len(advice_dict_top["title"])) + " : " + str((len(advice_dict_top["body"])))))
print((str(len(politics_dict_top["title"])) + " : " + str((len(politics_dict_top["body"])))))
print((str(len(offmychest_dict_top["title"])) + " : " + str((len(offmychest_dict_top["body"])))))
print((str(len(paranormal_dict_top["title"])) + " : " + str((len(paranormal_dict_top["body"])))))
print((str(len(science_dict_top["title"])) + " : " + (str(len(science_dict_top["body"])))))
print((str(len(anime_dict_top["title"]) )+ " : " + str((len(anime_dict_top["body"])))))
print((str(len(tech_dict_top["title"])) + " : " + str((len(tech_dict_top["body"])))))
print((str(len(photography_dict_top["title"])) + " : " + str((len(photography_dict_top["body"])))))
print((str(len(manga_dict_top["title"])) + " : " + str((len(manga_dict_top["body"])))))
print((str(len(music_dict_top["title"])) + " : " + str((len(music_dict_top["body"])))))
print((str(len(books_dict_top["title"])) + " : " + str((len(books_dict_top["body"])))))
print((str(len(general_dict_top["title"])) + " : " + str((len(general_dict_top["body"])))))

SUM_TITLE_TELEVISION = television_dict["title"] + television_dict_new["title"] + television_dict_top["title"]
SUM_BODY_TELEVISION = television_dict["body"] + television_dict_new["body"] + television_dict_top["body"]

SUM_TITLE_GAMING = gaming_dict["title"] + gaming_dict_new["title"] + gaming_dict_top["title"]
SUM_BODY_GAMING = gaming_dict["body"] + gaming_dict_new["body"] + gaming_dict_top["body"]

SUM_TITLE_CARS = cars_dict["title"] + cars_dict_new["title"] + cars_dict_top["title"]
SUM_BODY_CARS = cars_dict["body"] + cars_dict_new["body"] + cars_dict_top["body"]

SUM_TITLE_DIY = diy_dict["title"] + diy_dict_new["title"] + diy_dict_top["title"]
SUM_BODY_DIY = diy_dict["body"] + diy_dict_new["body"] + diy_dict_top["body"]

SUM_TITLE_ADVICE = advice_dict["title"] + advice_dict_new["title"] + advice_dict_top["title"]
SUM_BODY_ADVICE = advice_dict["body"] + advice_dict_new["body"] + advice_dict_top["body"]

SUM_TITLE_POLITICS = politics_dict["title"] + politics_dict_new["title"] + politics_dict_top["title"]
SUM_BODY_POLITICS = politics_dict["body"] + politics_dict_new["body"] + politics_dict_top["body"]

SUM_TITLE_OFFMYCHEST = offmychest_dict["title"] + offmychest_dict_new["title"] + offmychest_dict_top["title"]
SUM_BODY_OFFMYCHEST = offmychest_dict["body"] + offmychest_dict_new["body"] + offmychest_dict_top["body"]


SUM_TITLE_PARANORMAL = paranormal_dict["title"] + paranormal_dict_new["title"] + paranormal_dict_top["title"]
SUM_BODY_PARANORMAL = paranormal_dict["body"] + paranormal_dict_new["body"] + paranormal_dict_top["body"]

SUM_TITLE_SCIENCE = science_dict["title"] + science_dict_new["title"] + science_dict_top["title"]
SUM_BODY_SCIENCE = science_dict["body"] + science_dict_new["body"] + science_dict_top["body"]

SUM_TITLE_ANIME = anime_dict["title"] + anime_dict_new["title"] + anime_dict_top["title"]
SUM_BODY_ANIME = anime_dict["body"] + anime_dict_new["body"] + anime_dict_top["body"]

SUM_TITLE_TECH = tech_dict["title"] + tech_dict_new["title"] + tech_dict_top["title"]
SUM_BODY_TECH = tech_dict["body"] + tech_dict_new["body"] + tech_dict_top["body"]


SUM_TITLE_PHOTOGRAPHY = photography_dict["title"] + photography_dict_new["title"] + photography_dict_top["title"]
SUM_BODY_PHOTOGRAPHY = photography_dict["body"] + photography_dict_new["body"] + photography_dict_top["body"]

SUM_TITLE_MANGA = manga_dict["title"] + manga_dict_new["title"] + manga_dict_top["title"]
SUM_BODY_MANGA = manga_dict["body"] + manga_dict_new["body"] + manga_dict_top["body"]

SUM_TITLE_MUSIC = music_dict["title"] + music_dict_new["title"] + music_dict_top["title"]
SUM_BODY_MUSIC = music_dict["body"] + music_dict_new["body"] + music_dict_top["body"]

SUM_TITLE_BOOKS = books_dict["title"] + books_dict_new["title"] + books_dict_top["title"]
SUM_BODY_BOOKS = books_dict["body"] + books_dict_new["body"] + books_dict_top["body"]

SUM_TITLE_GENERAL = general_dict["title"] + general_dict_new["title"] + general_dict_top["title"]
SUM_BODY_GENERAL = general_dict["body"] + general_dict_new["body"] + general_dict_top["body"]

SUM_TITLE_TELEVISION = television_dict["title"] + television_dict_new["title"] + television_dict_top["title"]
SUM_BODY_TELEVISION = television_dict["body"] + television_dict_new["body"] + television_dict_top["body"]

SUM_TITLE_GAMING = gaming_dict["title"] + gaming_dict_new["title"] + gaming_dict_top["title"]
SUM_BODY_GAMING = gaming_dict["body"] + gaming_dict_new["body"] + gaming_dict_top["body"]

SUM_TITLE_CARS = cars_dict["title"] + cars_dict_new["title"] + cars_dict_top["title"]
SUM_BODY_CARS = cars_dict["body"] + cars_dict_new["body"] + cars_dict_top["body"]

SUM_TITLE_DIY = diy_dict["title"] + diy_dict_new["title"] + diy_dict_top["title"]
SUM_BODY_DIY = diy_dict["body"] + diy_dict_new["body"] + diy_dict_top["body"]

SUM_TITLE_ADVICE = advice_dict["title"] + advice_dict_new["title"] + advice_dict_top["title"]
SUM_BODY_ADVICE = advice_dict["body"] + advice_dict_new["body"] + advice_dict_top["body"]

SUM_TITLE_POLITICS = politics_dict["title"] + politics_dict_new["title"] + politics_dict_top["title"]
SUM_BODY_POLITICS = politics_dict["body"] + politics_dict_new["body"] + politics_dict_top["body"]

SUM_TITLE_OFFMYCHEST = offmychest_dict["title"] + offmychest_dict_new["title"] + offmychest_dict_top["title"]
SUM_BODY_OFFMYCHEST = offmychest_dict["body"] + offmychest_dict_new["body"] + offmychest_dict_top["body"]


SUM_TITLE_PARANORMAL = paranormal_dict["title"] + paranormal_dict_new["title"] + paranormal_dict_top["title"]
SUM_BODY_PARANORMAL = paranormal_dict["body"] + paranormal_dict_new["body"] + paranormal_dict_top["body"]

SUM_TITLE_SCIENCE = science_dict["title"] + science_dict_new["title"] + science_dict_top["title"]
SUM_BODY_SCIENCE = science_dict["body"] + science_dict_new["body"] + science_dict_top["body"]

SUM_TITLE_ANIME = anime_dict["title"] + anime_dict_new["title"] + anime_dict_top["title"]
SUM_BODY_ANIME = anime_dict["body"] + anime_dict_new["body"] + anime_dict_top["body"]

SUM_TITLE_TECH = tech_dict["title"] + tech_dict_new["title"] + tech_dict_top["title"]
SUM_BODY_TECH = tech_dict["body"] + tech_dict_new["body"] + tech_dict_top["body"]


SUM_TITLE_PHOTOGRAPHY = photography_dict["title"] + photography_dict_new["title"] + photography_dict_top["title"]
SUM_BODY_PHOTOGRAPHY = photography_dict["body"] + photography_dict_new["body"] + photography_dict_top["body"]

SUM_TITLE_MANGA = manga_dict["title"] + manga_dict_new["title"] + manga_dict_top["title"]
SUM_BODY_MANGA = manga_dict["body"] + manga_dict_new["body"] + manga_dict_top["body"]

SUM_TITLE_MUSIC = music_dict["title"] + music_dict_new["title"] + music_dict_top["title"]
SUM_BODY_MUSIC = music_dict["body"] + music_dict_new["body"] + music_dict_top["body"]

SUM_TITLE_BOOKS = books_dict["title"] + books_dict_new["title"] + books_dict_top["title"]
SUM_BODY_BOOKS = books_dict["body"] + books_dict_new["body"] + books_dict_top["body"]

SUM_TITLE_GENERAL = general_dict["title"] + general_dict_new["title"] + general_dict_top["title"]
SUM_BODY_GENERAL = general_dict["body"] + general_dict_new["body"] + general_dict_top["body"]

print(len(SUM_TITLE_TELEVISION))
print(len(SUM_BODY_TELEVISION))

print(len(SUM_TITLE_GAMING))
print(len(SUM_BODY_GAMING))

print(len(SUM_TITLE_CARS))
print(len(SUM_BODY_CARS))

print(len(SUM_TITLE_DIY))
print(len(SUM_BODY_DIY))

print(len(SUM_TITLE_ADVICE))
print(len(SUM_BODY_ADVICE))

print(len(SUM_TITLE_POLITICS))
print(len(SUM_BODY_POLITICS))

print(len(SUM_TITLE_OFFMYCHEST ))
print(len(SUM_BODY_OFFMYCHEST))


print(len(SUM_TITLE_PARANORMAL))
print(len(SUM_BODY_PARANORMAL))

print(len(SUM_TITLE_SCIENCE))
print(len(SUM_BODY_SCIENCE))

print(len(SUM_TITLE_ANIME))
print(len(SUM_BODY_ANIME))
print(len(SUM_TITLE_TECH))
print(len(SUM_BODY_TECH))


print(len(SUM_TITLE_PHOTOGRAPHY))
print(len(SUM_BODY_PHOTOGRAPHY))

print(len(SUM_TITLE_MANGA))
print(len(SUM_BODY_MANGA))
print(len(SUM_TITLE_MUSIC))
print(len(SUM_BODY_MUSIC))
print(len(SUM_TITLE_BOOKS))
print(len(SUM_BODY_BOOKS))

print(len(SUM_TITLE_GENERAL))
print(len(SUM_BODY_GENERAL))

SUM_TITLE_TELEVISION = SUM_TITLE_TELEVISION[0:1800]
SUM_BODY_TELEVISION = SUM_BODY_TELEVISION[0:1800]

SUM_TITLE_GAMING = SUM_TITLE_GAMING[0:1800]
SUM_BODY_GAMING = SUM_BODY_GAMING[0:1800]

SUM_TITLE_CARS = SUM_TITLE_CARS[0:1800]
SUM_BODY_CARS = SUM_BODY_CARS[0:1800]

SUM_TITLE_DIY = SUM_TITLE_DIY[0:1800]
SUM_BODY_DIY = SUM_BODY_DIY[0:1800]

SUM_TITLE_ADVICE = SUM_TITLE_ADVICE[0:1800]
SUM_BODY_ADVICE = SUM_BODY_ADVICE[0:1800]

SUM_TITLE_POLITICS = SUM_TITLE_POLITICS[0:1800]
SUM_BODY_POLITICS = SUM_BODY_POLITICS[0:1800]

SUM_TITLE_OFFMYCHEST  = SUM_TITLE_OFFMYCHEST[0:1800]
SUM_BODY_OFFMYCHEST = SUM_BODY_OFFMYCHEST[0:1800]


SUM_TITLE_PARANORMAL = SUM_TITLE_PARANORMAL[0:1800]
SUM_BODY_PARANORMAL = SUM_BODY_PARANORMAL[0:1800]

SUM_TITLE_SCIENCE = SUM_TITLE_SCIENCE[0:1800]
SUM_BODY_SCIENCE = SUM_BODY_SCIENCE[0:1800]

SUM_TITLE_ANIME = SUM_TITLE_ANIME[0:1800]
SUM_BODY_ANIME = SUM_BODY_ANIME[0:1800]


SUM_TITLE_TECH = SUM_TITLE_TECH[0:1800]
SUM_BODY_TECH = SUM_BODY_TECH[0:1800]


SUM_TITLE_PHOTOGRAPHY = SUM_TITLE_PHOTOGRAPHY[0:1800]
SUM_BODY_PHOTOGRAPHY = SUM_BODY_PHOTOGRAPHY[0:1800]

SUM_TITLE_MANGA = SUM_TITLE_MANGA[0:1800]
SUM_BODY_MANGA = SUM_BODY_MANGA[0:1800]

SUM_TITLE_MUSIC = SUM_TITLE_MUSIC[0:1800]
SUM_BODY_MUSIC = SUM_BODY_MUSIC[0:1800]

SUM_TITLE_BOOKS = SUM_TITLE_BOOKS[0:1800]
SUM_BODY_BOOKS = SUM_BODY_BOOKS[0:1800]

SUM_TITLE_GENERAL = SUM_TITLE_GENERAL[0:1800]
SUM_BODY_GENERAL = SUM_BODY_GENERAL[0:1800]

ALL_TITLE = SUM_TITLE_TELEVISION + SUM_TITLE_GAMING + SUM_TITLE_CARS + SUM_TITLE_DIY + SUM_TITLE_ADVICE + SUM_TITLE_POLITICS + SUM_TITLE_OFFMYCHEST + SUM_TITLE_PARANORMAL
ALL_TITLE = ALL_TITLE + SUM_TITLE_SCIENCE + SUM_TITLE_ANIME + SUM_TITLE_TECH + SUM_TITLE_PHOTOGRAPHY + SUM_TITLE_MANGA + SUM_TITLE_MUSIC + SUM_TITLE_BOOKS + SUM_TITLE_GENERAL

ALL_BODY = SUM_BODY_TELEVISION + SUM_BODY_GAMING + SUM_BODY_CARS + SUM_BODY_DIY + SUM_BODY_ADVICE + SUM_BODY_POLITICS + SUM_BODY_OFFMYCHEST + SUM_BODY_PARANORMAL
ALL_BODY = ALL_BODY + SUM_BODY_SCIENCE + SUM_BODY_ANIME + SUM_BODY_TECH + SUM_BODY_PHOTOGRAPHY + SUM_BODY_MANGA + SUM_BODY_MUSIC + SUM_BODY_BOOKS + SUM_BODY_GENERAL

print(len(ALL_TITLE))
print(len(ALL_BODY))

television_label = []
gaming_label = []
cars_label= []
diy_label = []
advice_label = []
politics_label = []
offmychest_label = []
paranormal_label = []
science_label = []
anime_label = []
tech_label = []
photography_label = []
manga_label = []
music_label = []
books_label = []
general_label = []
for i in range(1800):
  television_label.append('television')
  gaming_label.append('gaming')
  cars_label.append('cars')
  diy_label.append('diy')
  advice_label.append('advice')
  politics_label.append('politics')
  offmychest_label.append('offmychest')
  paranormal_label.append('paranormal')
  science_label.append('science')
  anime_label.append('anime')
  tech_label.append('tech')
  photography_label.append('photography')
  manga_label.append('manga')
  music_label.append('music')
  books_label.append('books')
  general_label.append('general')

ALL_LABEL = television_label + gaming_label + cars_label + diy_label + advice_label + politics_label
ALL_LABEL = ALL_LABEL + offmychest_label + paranormal_label + science_label + anime_label + tech_label + photography_label + manga_label + music_label + books_label + general_label

print(len(ALL_LABEL))

data = {'TITLE': ALL_TITLE, 'BODY': ALL_BODY, 'LABEL': ALL_LABEL}

df = pd.DataFrame(data)

f = open("reddit_posts.csv", "w")
f.write(df.to_csv())
f.close()

