# -*- coding: utf-8 -*-
"""SaliencyMap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WeTdYO-8ahYdwqEOOHCxZ4wcN47AnDFa
"""

import cv2
import matplotlib.pyplot as plt
import nilearn.datasets as ds
from nilearn import plotting, image
import nibabel as nb

image = cv2.imread(r"D:\stairs.jpg")
saliency = cv2.saliency.StaticSaliencySpectralResidual_create()
(success, saliencyMap) = saliency.computeSaliency(image_3d)
saliencyMap = (saliencyMap * 255).astype("uint8")
plt.imshow(saliencyMap)
plt.show()



abide = ds.fetch_abide_pcp(n_subjects=25)

image = nb.load("/root/nilearn_data/ABIDE_pcp/cpac/nofilt_noglobal/Pitt_0050006_func_preproc.nii.gz")

data = image.get_data()

data.shape

image_3d = data[:, :, :, 0]

image_3d.shape

plotting.plot_img(image_3d)

help(plotting.plot_prob_atlas)

type(abide)

