# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13gGJrdosnFM2MykKior-_KkQ3XNaewwY
"""

!git clone https://github.com/ieee8023/covid-chestxray-dataset.git

import pandas as pd
import numpy as np
from keras.preprocessing.image import load_img, img_to_array
import os

imageMd = pd.read_csv("/content/covid-chestxray-dataset/metadata.csv")
imageMd.head()

imagesFn = imageMd["filename"].values

imagesArray = []

for (imageFn, i) in zip(imagesFn, range(len(imagesFn))):
  if os.path.exists(os.path.join("/content/covid-chestxray-dataset/images", imageFn)):
    imagesArray.append(img_to_array(load_img(os.path.join("/content/covid-chestxray-dataset/images", imageFn))))

